#
#        Title:      base.conf
#        Brief:      Configurações básicas do Tmux
#        Path:       /home/jkyon/.config/tmux/conf.d/base.conf
#        Author:     John Kennedy a.k.a. jKyon
#        Created:    2025-04-15
#        Updated:    2026-03-17
#        Notes:
#


# ---------- [ Configurações Essenciais ] ----------
set -g default-terminal "xterm-256color"       # Mais compatível que tmux-256color
set -as terminal-overrides ',xterm-256color:RGB,:xterm-256color:delete=\E[3~'


# ---------- [ Controle do Mouse ] ----------
set -g mouse on
set -g default-command 'zsh'


# ---------- [ Compatibilidade com alacritty + zsh ] ----------
set -g xterm-keys on
set -s extended-keys on

# ---------- [ clipboard options ] ----------
set -g allow-passthrough on
set -g set-clipboard on
