#
#        Title:      keys.conf
#        Brief:      Pesonal Tmux keybindings for enhanced navigation and editing efficiency.
#        Path:       /home/jkyon/.config/tmux/conf.d/keys.conf
#        Author:     John Kennedy a.k.a. jKyon
#        Created:    2025-04-15
#        Updated:    2026-03-17
#        Notes:
#

#
unbind-key -n PageUp
unbind-key -n PageDown

# ------------------------------------------------------------------------

# Navegação em linhas
bind-key -n Home   send-keys "\033[H"   # Home   → início da linha
bind-key -n End    send-keys "\033[F"   # End    → fim da linha
bind-key -n C-Home send-keys "\033[1;5H" # Ctrl+Home → início do buffer
bind-key -n C-End  send-keys "\033[1;5F" # Ctrl+End  → fim do buffer
# bind-key -n Delete send-keys C-d # Delete

# Navegação por palavras
bind-key -n C-Left send-keys Escape b # Ctrl + ← (Voltar uma palavra)
bind-key -n C-Right send-keys Escape f # Ctrl + → (Avançar uma palavra)

# Atalhos específicos
bind-key -n M-Delete send-keys C-w # Alt + Backspace (Apagar palavra anterior)
bind-key -n M-Down send-keys Tab # Alt + ↓ (Rotação de completions)
bind-key -n M-Right send-keys Right # Aceitar sugestão (→)

# Shift + Delete (apaga a linha inteira)
bind-key -n S-Delete send-keys C-a C-k

# ------------------------------------------------------------------------