# ~/.config/tmux/conf.d/theme.conf

# # Configurações de tema
# # Configure the Catppuccin plugin
set -g @catppuccin_flavor "frappe"
set -g @catppuccin_window_status_style "none"
set -g @catppuccin_window_number_position "right"
set -ogq @catppuccin_window_flags "text"

# # Load Catppuccin
set -g @catppuccin_status_right_separator_inverse "no"
run ~/.config/tmux/plugins/tmux/catppuccin.tmux

# # Make the status line pretty and add some modules
set -g status on
set -g status-right-length 100
set -g status-left-length 100

# # Remove window names from status line
set -g window-status-format ""
set -g window-status-current-format ""

# # Configure status modules
set -g status-left "#[fg=#{E:@thm_fg},bg=#{E:@thm_surface_0}]#{E:@catppuccin_session_text} #[fg=#{E:@catppuccin_session_color},bg=#{E:@thm_surface_0}]#{@catppuccin_status_middle_separator}#[fg=#{E:@thm_crust},bg=#{E:@catppuccin_session_color}] #{E:@catppuccin_session_icon}#[fg=#{E:@catppuccin_session_color},bg=#{E:@thm_surface_0}]#[fg=#{E:@thm_fg},bg=#{E:@thm_surface_0}]#{E:@catppuccin_application_text} #[fg=#{E:@catppuccin_application_color},bg=#{E:@thm_surface_0}]#{@catppuccin_status_middle_separator}#[fg=#{E:@thm_crust},bg=#{E:@catppuccin_application_color}] #{E:@catppuccin_application_icon}#[fg=#{E:@catppuccin_application_color},bg=default]"

set -g status-right "#[fg=#{E:@catppuccin_user_color},bg=default]#[fg=#{E:@thm_crust},bg=#{E:@catppuccin_user_color}] #{E:@catppuccin_user_icon} #[fg=#{E:@catppuccin_user_color},bg=#{E:@thm_surface_0}]#{@catppuccin_status_middle_separator}#[fg=#{E:@thm_fg},bg=#{E:@thm_surface_0}]#{E:@catppuccin_user_text} #[fg=#{E:@catppuccin_host_color},bg=#{E:@thm_surface_0}]#[fg=#{E:@thm_crust},bg=#{E:@catppuccin_host_color}] #{E:@catppuccin_host_icon} #[fg=#{E:@catppuccin_host_color},bg=#{E:@thm_surface_0}]#{@catppuccin_status_middle_separator}#[fg=#{E:@thm_fg},bg=#{E:@thm_surface_0}]#{E:@catppuccin_host_text} "

# Customize user and directory text
set -g @catppuccin_user_text "#{user}"
